name: cached_network_svg_image
description: A Flutter package for caching SVG images.
version: 1.3.0
homepage: https://github.com/mindylog/cached_network_svg_image
publish_to: https://brewery.mindy.kr

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
